# -*- coding: utf-8 -*-
"""data science batch 2 (Aditya Masand).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_arzUVkWNhII5Ef4XWVLxjpEH-sLfgk
"""

a=10
b=21
print(a+b)
print(a*b)
print(a/b)
print(a>b)
print(b>a)
print(a>=b)
print(b>=a)
print(a and b)
print(a or b)
print(not a)
print(not b)
print(a!=b)

print("this is a boy")

a=input("enter a number") #to take input we use input ("statement")
print(a)

#to take input of an integer variable we  do typecasting of input() as by default the input takes a string value
#for eg
a=int(input("enter a number"))
print(a)

#day 2

#multiplication table of 2
for i in range(1,11):
   print("2 x",i,"=",2*i)

#find odd and even nos between 0 and 100
for i in range(0,101):
    if(i%2==0):
       print("even number is:",i)

#sum of all even nos
sum=0
for i in range(0,101):
    if(i%2==0):
      sum=sum+i
print("sum of all even nos:",sum)

#student grade system using for loop
marks=int(input("enter marks:"))
if(marks>=80 and marks<=100):
   print("GRADE A")
elif(marks>=60 and marks<=79):
  print("GRADE B")
elif(marks>=50 and marks<=59):
  print("GRADE C")
else:
  print("you failed")

#find factorial of 5
fact=1
for i in range(1,6):
  fact=fact*i;
print("factorial of 5 is:",fact)

#find largest number from 20,21,70,80,64,36
numbers=[20,21,70,80,64,36]
n=6
sum=0
for i in numbers:
    sum+=i
    avg=(sum)/n
print("avg is:",avg)

#print the pattern
#*
#**
#***
#*****
#******
for i in range (1,7):
    for j in range(1,i+1):
        print("*",end="")
    print("\n")

#find pythagorean triplets
#find prime numbers 1 to 100
#difference between  S1 and CI if p=1000 and r=10% t=3
#find area and perimeter of circle
#find diagonal of rectangle if l=3 and b=5

#pythagorean triplets
a=int(input("enter first number:"))
b=int(input("enter second number:"))
c=int(input("enter third number:"))
if(a*a+b*b==c*c):
    print("pythogorean triplets are:",a,b,c)
else:
    print("pythogorean triplets do not exist")

# prime numbers between 1 to 100
print("Prime numbers between 1 and 100:")
for i in range(2, 101):
    is_prime = True
    for j in range(2, int(i**0.5) + 1):
        if i % j == 0:
            is_prime = False
            break
    if is_prime:
        print(i, end=" ")

#difference between si and ci if p=1000 and r=10% and t=3
p=1000
r=10
t=3
si=(p*r*t)/100
ci=p*(pow(1+(r/100),t))-p
print(si)
print(ci)
print("difference between si and ci is:",ci-si)

#find area and perimeter of a circle
pi=3.14
r=int(input('enter radius of a circle:'))
area=pi*r*r
perimeter=2*pi*r
print("area is :",area)
print("perimeter is:",perimeter)

#find diagonal of a rectangle with l=3 and b=5
l=3
b=5
diagonal=(l*l+b*b)**0.5
print("diagonal is:",diagonal)

#print pattern
#*
#**
#***
#****
#*****
#******
#*****
#****
#***
#**
#*
for i in range (1,12):
  if(i<=6):
    for j in range(1,i+1):
        print("*",end="")
  else:
       for j in range(1,13-i):
        print("*",end="")
  print("\n")

#day 3

name=input('enter your name:')
print(f" Hello!{name},How may I Assist You ")
print("What would you like to order")
menu = {
    "coffee": 10,
    "tea": 25,
    "maggie": 30,
    "sandwich": 45,
    "soda": 20
}

print("\n--- Our Menu ---")
for item, price in menu.items():
    print(f"{item.capitalize()}: ${price:.2f}")
print("------------------")

order_list = []
total_bill = 0

while True:
    item_name = input("\nEnter the item you want to order (or 'done' to finish): ").lower()
    if item_name == 'done':
        break
    elif item_name in menu:
        order_list.append(item_name)
        total_bill += menu[item_name]
        print(f"{item_name.capitalize()} added to your order.")
    else:
        print("Sorry, that item is not on our menu. Please choose from the available items.")

if order_list:
    print("\n--- Your Order ---")
    for item in order_list:
        print(f"- {item.capitalize()}")
    print(f"------------------")
    print(f"Your total bill is: ${total_bill:.2f}")
    print("Thank you for your order!")
else:
    print("You didn't order anything. Goodbye!")